### ISSUE TITLE
'liteloader-installer-1.8.0-00-SNAPSHOT' does not work with 'forge-1.8-11.14.3.1450-installer' or 'forge-1.8-11.14.3.1449-installer'

### ISSUE THREAD

**Issue by robjac** [Mumfrey/LiteLoaderInstaller#4]
'liteloader-installer-1.8.0-00-SNAPSHOT' does not work with 
'forge-1.8-11.14.3.1450-installer' or 
'forge-1.8-11.14.3.1449-installer'

But I can confirm that it works with forge-1.8-11.14.1.1371-installer. 

Just thought you all should know. -- Any solutions please send them my way!

-Cheers
-Robbie

**Comment by Mumfrey** [comment]
Your issue doesn't make sense and in any case this isn't the place for bug reports. Please use the [issue tracker](https://www.assembla.com/spaces/liteloader/support/tickets) for liteloader issues. Telling me that "x.x.x-SNAPSHOT" doesn't work is completely meaningless, because all of the CI builds have the same file name, you need to actually ensure that you have downloaded [the most recent version](http://jenkins.liteloader.com/job/LiteLoaderInstaller/lastSuccessfulBuild/) and report the build number of the version you downloaded (as you can see, the current build is **49**).

The latest build is working with Forge, so I will consider this issue invalid. Please use the latest snapshot.

**Comment by robjac** [comment]
Jesus Christ man; I didn't mean to offend you. GitHub is a place to discuss
code; I wasn't trying to piss you off.

I'll obviously try again -- And make sure never to try to contact you via
GitHub. You needn't ever be this rude to somebody asking a question on a
Social coding site.

-Robbie Jacobs

**Comment by Mumfrey** [comment]
You didn't offend me at all, I was just trying to guide you in the right direction, sorry if you mistook a terse reply for a harsh one.

**Comment by robjac** [comment]
Yeah it was a bit harsh to read. My colleagues and I run a Minecraft
tournament at work; the entire software engineering team plays every
Thursday. lite loader was a crucial piece to our private server. I will
direct all my support questions to your Jenkins build web UI from now on.
-Robbie Jacobs
Senior Web Developer I / Lead UI Engineer II
LiveNation

**Comment by Mumfrey** [comment]
As I mentioned above, for liteloader issues you can use the [issue tracker](https://www.assembla.com/spaces/liteloader/support/tickets) on assembla, but if you're having issues with Forge then you should find that using the latest snapshot fixes the issue.

**Comment by robjac** [comment]
Thank you I appreciate your reply and instructions detailed. I will let you
know how that goes at work today. On assembla not github or the Jenkins
build server. My mistake.

Cheers,
Robbie Jacobs
Senior Web Designer II / Lead UI Engineer I
@ LiveNation

**Comment by liach** [comment]
Mumfrey, what's the difference between [this link](https://www.assembla.com/spaces/liteloader/tickets) and [the link you provided](https://www.assembla.com/spaces/liteloader/support/tickets)? I posted an issue on the previous link... Sorry for the inconvenience I've made.

**Comment by Mumfrey** [comment]
Nothing really, the one is just the place to submit new tickets and the other lists open tickets. I'm assuming that you're _Sollace_ on assembla?

Except for critical things like retaining compatibility with current Forge/FML, _all_ of my projects are on hold _except_ for Sponge until after Minecon, since preparing Sponge for exhibiting at Minecon is the top priority. This has been the case for the last few months as we are all pushing to get Sponge to a release-ready state.
